spring.application.name=api

#spring.datasource.url=jdbc:mysql://localhost:3306/jacke_cursos
#spring.datasource.username=root
#spring.datasource.password=stevejobs
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Banco H2 para testes
spring.datasource.url=jdbc:h2:mem:teste
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console

jwt.secret=jackeline_api_secret_key_muito_segura_2026_1234567890
jwt.expiration-ms=86400000

server.port=8081
