spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/jacke_cursos
spring.datasource.username=root
spring.datasource.password=Sp#0705#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# WhatsApp Gateway (Node.js WPPConnect)
whatsapp.gateway.base-url=http://localhost:21465